#!/usr/bin/env bash

get_feature_sessions() {
    tmux list-sessions -F "#{session_name}" 2>/dev/null | grep -v "^ws-"
}

result=$(get_feature_sessions | fzf --print-query --prompt="feature: ")

query=$(printf "%s" "$result" | head -1)
selected=$(printf "%s" "$result" | sed -n '2p')

if [[ -z $query ]]; then
    exit 0
fi

if [[ -n $selected ]]; then
    session_name="$selected"
else
    session_name=$(echo "$query" | tr ' .' '_')
fi

tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -ds "$session_name" -c "$HOME"
    tmux attach-session -t "$session_name"
    exit 0
fi

if ! tmux has-session -t="$session_name" 2>/dev/null; then
    tmux new-session -ds "$session_name" -c "$HOME"
fi

if [[ -z $TMUX ]]; then
    tmux attach-session -t "$session_name"
else
    tmux switch-client -t "$session_name"
fi
